import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Brain, Check, ChevronDown, HeartHandshake, Instagram, MessageCircle, Menu, Sparkles, Stethoscope, X } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Espaço Mente Brilhante | Neuropsicologia e Saúde Mental" },
      { name: "description", content: "Ciência, acolhimento e estratégias para promover desenvolvimento integral e qualidade de vida." },
      { property: "og:title", content: "Espaço Mente Brilhante" },
      { property: "og:description", content: "Cuidar da mente é transformar vidas. Atendimento presencial e online." },
    ],
  }),
  component: Index,
});

const wa = "https://wa.me/5592991819513";
const services = [
  ["🧩", "Atendimento para TEA", "Acolhimento e estratégias individualizadas para diferentes necessidades."],
  ["🧠", "Atendimento para TDAH", "Acompanhamento voltado à compreensão e ao desenvolvimento de estratégias."],
  ["📚", "Transtornos e dificuldades de aprendizagem", "Investigação e intervenção considerando a singularidade de cada pessoa."],
  ["💙", "Saúde Mental", "Espaço de escuta e cuidado para promover qualidade de vida."],
  ["✨", "TOD", "Atendimento para Transtorno Opositivo Desafiador com olhar individualizado."],
  ["🌿", "Ansiedade", "Acolhimento e acompanhamento para compreender desafios e desenvolver recursos."],
  ["🌼", "Depressão", "Cuidado humanizado e individualizado durante a jornada de acompanhamento."],
  ["📋", "Avaliação Neuropsicológica", "Avaliação estruturada para compreender aspectos cognitivos, emocionais e funcionais."],
  ["💬", "Atendimento Psicológico", "Escuta profissional em um ambiente seguro, acolhedor e respeitoso."],
  ["🧩", "Intervenção ABA", "Estratégias baseadas em princípios da Análise do Comportamento Aplicada."],
];

const testimonials = [
  ["“Fui recebida com muito acolhimento e atenção. Me senti segura desde o primeiro atendimento.”", "Paciente"],
  ["“O atendimento foi muito cuidadoso e individualizado. Conseguimos entender melhor nossas necessidades.”", "Familiar"],
  ["“A experiência foi muito positiva. Profissional atenciosa, clara e humana.”", "Paciente"],
  ["“Finalmente encontramos um espaço onde nossa família se sentiu realmente compreendida.”", "Familiar"],
];

function Index() {
  const [mobile, setMobile] = useState(false);
  const [service, setService] = useState(0);
  const [testimonial, setTestimonial] = useState(0);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  useEffect(() => { const t = setInterval(() => setService(s => (s + 1) % services.length), 3500); return () => clearInterval(t); }, []);
  useEffect(() => { const t = setInterval(() => setTestimonial(s => (s + 1) % testimonials.length), 4500); return () => clearInterval(t); }, []);
  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobile(false); };
  return <div className="min-h-screen overflow-x-hidden bg-[#080706] text-[#f8f4ec]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-[#c89b4a]/20 bg-[#080706]/90 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
        <button onClick={() => go("inicio")} className="group flex items-center gap-3 text-left"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-[#c89b4a]/50 bg-[#c89b4a]/10 text-[#e1b65d]"><Brain /></span><span><b className="block font-serif text-lg tracking-wide text-[#e1b65d]">ESPAÇO MENTE</b><small className="text-[10px] uppercase tracking-[.3em] text-white/60">Brilhante</small></span></button>
        <nav className="hidden items-center gap-7 text-sm font-medium lg:flex"><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button><button onClick={() => go("faq")}>Dúvidas</button><a href={wa} target="_blank" rel="noreferrer" className="rounded-full bg-[#c89b4a] px-5 py-2.5 font-bold text-[#100d09] transition hover:scale-105">Agendar atendimento</a></nav>
        <button className="lg:hidden" onClick={() => setMobile(!mobile)} aria-label="Abrir menu">{mobile ? <X /> : <Menu />}</button>
      </div>
      <AnimatePresence>{mobile && <motion.nav initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden border-t border-[#c89b4a]/20 bg-[#0e0c0a] px-5 pb-5 lg:hidden"><div className="flex flex-col gap-4 pt-5"><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button><button onClick={() => go("faq")}>Dúvidas</button><a href={wa} target="_blank" rel="noreferrer" className="rounded-full bg-[#c89b4a] px-5 py-3 text-center font-bold text-black">Agendar pelo WhatsApp</a></div></motion.nav>}</AnimatePresence>
    </header>

    <main id="inicio">
      <section className="relative flex min-h-[760px] items-center px-5 pb-20 pt-36 lg:min-h-screen lg:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_40%,rgba(200,155,74,.16),transparent_35%),radial-gradient(circle_at_15%_80%,rgba(255,255,255,.04),transparent_30%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]">
        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#c89b4a]/30 bg-[#c89b4a]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-[#e1b65d]"><Sparkles className="h-4 w-4" /> Atendimento presencial e online</div><h1 className="max-w-4xl font-serif text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">Cuidar da mente é <span className="text-[#d9ad5a]">transformar vidas.</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/70 sm:text-xl">Ciência, acolhimento e estratégias para promover o desenvolvimento integral e a qualidade de vida.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={wa} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#c89b4a] px-7 py-4 font-bold text-black shadow-[0_15px_45px_rgba(200,155,74,.18)] transition hover:scale-[1.03]">Agendar meu atendimento <ArrowRight className="h-5 w-5" /></a><button onClick={() => go("servicos")} className="rounded-full border border-white/20 px-7 py-4 font-semibold transition hover:bg-white/10">Conhecer os serviços</button></div><div className="mt-9 flex flex-wrap gap-5 text-sm text-white/60"><span className="flex items-center gap-2"><Check className="text-[#d9ad5a]" /> Atendimento humanizado</span><span className="flex items-center gap-2"><Check className="text-[#d9ad5a]" /> Plano individualizado</span></div></motion.div>
        <motion.div initial={{ opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8, delay: .15 }} className="relative mx-auto w-full max-w-md"><div className="aspect-[4/5] rounded-[2rem] border border-[#c89b4a]/30 bg-gradient-to-br from-[#201b14] via-[#11100d] to-[#080706] p-3 shadow-[0_30px_100px_rgba(0,0,0,.5)]"><div className="flex h-full flex-col items-center justify-center rounded-[1.5rem] border border-white/5 bg-[#0d0b09] p-8 text-center"><div className="mb-6 flex h-24 w-24 items-center justify-center rounded-full border border-[#c89b4a]/40 bg-[#c89b4a]/10"><Brain className="h-12 w-12 text-[#d9ad5a]" /></div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d9ad5a]">Espaço Mente Brilhante</p><h2 className="mt-4 font-serif text-3xl">Um espaço para compreender, acolher e desenvolver.</h2><p className="mt-4 text-sm leading-relaxed text-white/50">Cada pessoa é única. O cuidado também deve ser.</p></div></div><div className="absolute -bottom-5 -left-5 rounded-2xl border border-[#c89b4a]/30 bg-[#15120e]/95 px-5 py-4 backdrop-blur"><p className="text-xs text-white/50">Responsável técnica</p><p className="font-bold text-[#e1b65d]">Francineia Magalhães</p><p className="text-xs text-white/60">Neuropsicóloga Clínica · CRP 10/06883</p></div></motion.div>
      </div></section>

      <section className="border-y border-[#c89b4a]/15 bg-[#11100d] px-5 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3"><div className="rounded-2xl border border-white/10 p-7"><HeartHandshake className="text-[#d9ad5a]" /><h3 className="mt-5 font-serif text-2xl">Acolhimento</h3><p className="mt-2 text-sm leading-relaxed text-white/55">Um atendimento que respeita sua história, seu tempo e suas necessidades.</p></div><div className="rounded-2xl border border-white/10 p-7"><Brain className="text-[#d9ad5a]" /><h3 className="mt-5 font-serif text-2xl">Olhar individual</h3><p className="mt-2 text-sm leading-relaxed text-white/55">Estratégias construídas considerando a singularidade de cada pessoa.</p></div><div className="rounded-2xl border border-white/10 p-7"><Stethoscope className="text-[#d9ad5a]" /><h3 className="mt-5 font-serif text-2xl">Ciência + cuidado</h3><p className="mt-2 text-sm leading-relaxed text-white/55">Conhecimento profissional aliado a uma experiência humana e respeitosa.</p></div></div></section>

      <section id="sobre" className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d9ad5a]">Quem sou</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Francineia Magalhães</h2><p className="mt-3 text-[#d9ad5a]">Neuropsicóloga Clínica · CRP 10/06883</p><div className="mt-7 space-y-5 text-white/65 leading-relaxed"><p>Meu propósito é oferecer um espaço de acolhimento, compreensão e cuidado, unindo conhecimento científico a uma escuta verdadeiramente humanizada.</p><p>Cada pessoa chega com uma história, desafios e potencialidades diferentes. Por isso, o acompanhamento é pensado de forma individualizada, respeitando o momento e as necessidades de cada paciente.</p><p>O objetivo é caminhar junto, compreender o que está acontecendo e construir estratégias que façam sentido para a vida real.</p></div><a href={wa} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-full border border-[#c89b4a]/50 px-6 py-3 font-semibold text-[#e1b65d] hover:bg-[#c89b4a]/10">Falar com Francineia</a></div><div className="rounded-[2rem] border border-[#c89b4a]/20 bg-[#12100d] p-10"><div className="mb-6 h-1 w-16 bg-[#c89b4a]" /><p className="font-serif text-3xl leading-snug">“Cada pessoa é única. Nosso compromisso é acolher, compreender e revelar o melhor de cada história.”</p><p className="mt-6 text-sm text-white/45">Espaço Mente Brilhante</p></div></div></section>

      <section id="servicos" className="bg-[#f4efe7] px-5 py-24 text-[#17130e] lg:px-8"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#8b672e]">Nossos serviços</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Cuidado para diferentes necessidades</h2><p className="mx-auto mt-4 max-w-2xl text-[#17130e]/60">Conheça as possibilidades de atendimento e encontre o suporte mais adequado para você ou sua família.</p></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{services.map(([icon,title,text], i) => <motion.a href={wa} target="_blank" rel="noreferrer" key={title} whileHover={{ y: -6 }} className={`rounded-2xl border p-6 transition ${i === service ? "border-[#b88638] bg-white shadow-xl" : "border-[#17130e]/10 bg-white/60"}`}><span className="text-3xl">{icon}</span><h3 className="mt-5 font-serif text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#17130e]/60">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold uppercase tracking-wider text-[#8b672e]">Agendar <ArrowRight className="h-4 w-4" /></span></motion.a>)}</div><div className="mt-8 flex justify-center gap-2">{services.map((_,i)=><button key={i} aria-label={`Serviço ${i+1}`} onClick={()=>setService(i)} className={`h-2 rounded-full transition-all ${i===service?"w-8 bg-[#b88638]":"w-2 bg-[#17130e]/20"}`} />)}</div></div></section>

      <section id="como" className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d9ad5a]">Como funciona</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Um cuidado pensado para você.</h2><p className="mt-5 text-white/55">Não existe um caminho pronto que sirva para todo mundo. O acompanhamento parte da compreensão das suas necessidades para construir os próximos passos.</p></div><div className="mt-14 grid gap-5 md:grid-cols-4">{[["01","Conversa inicial","Entendemos sua história, suas necessidades e o que trouxe você até aqui."],["02","Compreensão","Investigamos e organizamos as informações relevantes para o cuidado."],["03","Plano individualizado","As estratégias são definidas de acordo com cada pessoa e objetivo."],["04","Acompanhamento","Seguimos juntos, avaliando o processo e ajustando o cuidado quando necessário."]].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/10 bg-white/[.03] p-7"><span className="text-4xl font-serif text-[#d9ad5a]">{n}</span><h3 className="mt-7 font-serif text-2xl">{t}</h3><p className="mt-3 text-sm leading-relaxed text-white/50">{d}</p></div>)}</div><div className="mt-10 text-center"><a href={wa} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#c89b4a] px-7 py-4 font-bold text-black">Quero começar meu cuidado <ArrowRight /></a></div></div></section>

      <section className="bg-[#11100d] px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-2"><div className="rounded-3xl border border-[#c89b4a]/20 bg-[#18150f] p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d9ad5a]">Quando procurar ajuda?</p><h2 className="mt-4 font-serif text-3xl sm:text-4xl">Você não precisa esperar ficar insuportável.</h2><p className="mt-5 leading-relaxed text-white/55">Dificuldades de atenção, aprendizagem, emoções, comportamento ou relações podem gerar dúvidas e impactar a rotina. Buscar orientação profissional pode ser um passo importante para compreender melhor o que está acontecendo.</p><a href={wa} target="_blank" rel="noreferrer" className="mt-7 inline-flex rounded-full border border-[#c89b4a]/50 px-6 py-3 font-semibold text-[#e1b65d]">Conversar sobre meu caso</a></div><div className="rounded-3xl border border-white/10 p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d9ad5a]">Um olhar além do diagnóstico</p><h2 className="mt-4 font-serif text-3xl sm:text-4xl">Antes de qualquer rótulo, existe uma pessoa.</h2><p className="mt-5 leading-relaxed text-white/55">O cuidado busca compreender potencialidades, dificuldades, contexto e objetivos. O diagnóstico, quando parte do processo profissional, é uma ferramenta para compreender — não para definir quem você é.</p></div></div></div></section>

      <section id="depoimentos" className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d9ad5a]">Depoimentos</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Experiências que acolhem</h2><div className="relative mt-12 min-h-[250px] overflow-hidden rounded-3xl border border-[#c89b4a]/20 bg-[#11100d] p-8 sm:p-12"><AnimatePresence mode="wait"><motion.div key={testimonial} initial={{ opacity: 0, x: 35 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -35 }} className="flex min-h-[180px] flex-col items-center justify-center"><div className="mb-6 text-3xl text-[#d9ad5a]">★★★★★</div><p className="font-serif text-2xl leading-relaxed sm:text-3xl">{testimonials[testimonial]?.[0]}</p><p className="mt-6 text-sm text-white/40">— {testimonials[testimonial]?.[1]}</p></motion.div></AnimatePresence></div><div className="mt-6 flex justify-center gap-2">{testimonials.map((_,i)=><button key={i} onClick={()=>setTestimonial(i)} aria-label={`Depoimento ${i+1}`} className={`h-2 rounded-full ${i===testimonial?"w-8 bg-[#d9ad5a]":"w-2 bg-white/20"}`} />)}</div></div></section>

      <section id="faq" className="bg-[#f4efe7] px-5 py-24 text-[#17130e] lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#8b672e]">Perguntas frequentes</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Dúvidas comuns</h2></div><div className="mt-12 divide-y divide-[#17130e]/10 rounded-3xl bg-white px-6">{[["O atendimento é presencial ou online?","Os atendimentos podem ser realizados presencialmente ou online, conforme a modalidade disponível e adequada ao caso."],["Como saber qual atendimento é indicado?","O primeiro contato ajuda a compreender sua necessidade e orientar sobre o serviço mais adequado."],["O atendimento é individualizado?","Sim. Cada pessoa possui necessidades e objetivos diferentes, por isso o acompanhamento é construído de forma individualizada."],["Como agendar?","Clique em qualquer botão de WhatsApp da página para iniciar uma conversa e verificar disponibilidade."],["O Espaço atende crianças e adultos?","Os serviços são direcionados conforme a necessidade e a atuação profissional. No contato inicial, podemos orientar sobre a melhor possibilidade para cada caso."]].map(([q,a],i)=><div key={q}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} className="flex w-full items-center justify-between gap-5 py-6 text-left font-bold">{q}<ChevronDown className={`shrink-0 transition ${openFaq===i?"rotate-180":""}`} /></button><AnimatePresence>{openFaq===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden pb-6 text-sm leading-relaxed text-[#17130e]/60">{a}</motion.p>}</AnimatePresence></div>)}</div><div className="mt-10 text-center"><a href={wa} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#17130e] px-7 py-4 font-bold text-white">Tirar minhas dúvidas no WhatsApp <MessageCircle /></a></div></div></section>
    </main>

    <footer className="border-t border-[#c89b4a]/20 bg-[#080706] px-5 py-14 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><p className="font-serif text-2xl text-[#e1b65d]">Espaço Mente Brilhante</p><p className="mt-3 max-w-sm text-sm leading-relaxed text-white/45">Cuidar da mente é transformar vidas. Ciência, acolhimento e estratégias para promover desenvolvimento integral e qualidade de vida.</p></div><div><p className="font-bold">Atendimento</p><p className="mt-3 text-sm text-white/50">Presencial e online</p><p className="mt-1 text-sm text-white/50">Francineia Magalhães</p><p className="mt-1 text-sm text-white/50">Neuropsicóloga Clínica · CRP 10/06883</p></div><div><p className="font-bold">Contato</p><a href={wa} target="_blank" rel="noreferrer" className="mt-3 block text-sm text-[#e1b65d]">(92) 99181-9513</a><a href="https://instagram.com/francineia_magalhaes" target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-sm text-white/60"><Instagram className="h-4 w-4" /> @francineia_magalhaes</a></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-6 text-xs text-white/30">© {new Date().getFullYear()} Espaço Mente Brilhante. Todos os direitos reservados.</div></footer>
    <a href={wa} target="_blank" rel="noreferrer" aria-label="WhatsApp" className="fixed bottom-5 right-5 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-[#25D366] text-white shadow-[0_10px_35px_rgba(37,211,102,.3)] transition hover:scale-110"><MessageCircle /></a>
  </div>;
}
