import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Brain, Check, ChevronDown, HeartHandshake, Instagram, MessageCircle, Menu, Sparkles, Stethoscope, X } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Espaço Mente Brilhante | Neuropsicologia e Saúde Mental" },
    { name: "description", content: "Ciência, acolhimento e estratégias para promover desenvolvimento integral e qualidade de vida." },
  ] }), component: Index,
});

const wa = "https://wa.me/5592991819513";
const services = [
  ["🧩", "Atendimento para TEA", "Acolhimento e estratégias individualizadas."],
  ["🧠", "Atendimento para TDAH", "Compreensão e estratégias para diferentes necessidades."],
  ["📚", "Dificuldades de aprendizagem", "Investigação e intervenção individualizada."],
  ["💙", "Saúde Mental", "Escuta e cuidado para promover qualidade de vida."],
  ["✨", "TOD", "Atendimento com olhar individualizado."],
  ["🌿", "Ansiedade", "Acolhimento e desenvolvimento de recursos."],
  ["🌼", "Depressão", "Cuidado humanizado durante o acompanhamento."],
  ["📋", "Avaliação Neuropsicológica", "Compreensão de aspectos cognitivos, emocionais e funcionais."],
  ["💬", "Atendimento Psicológico", "Escuta profissional em ambiente seguro."],
  ["🧩", "Intervenção ABA", "Estratégias baseadas em princípios da Análise do Comportamento Aplicada."],
];
const testimonials = [
  ["Fui recebida com muito acolhimento e atenção. Me senti segura desde o primeiro atendimento.", "Paciente"],
  ["O atendimento foi muito cuidadoso e individualizado. Conseguimos entender melhor nossas necessidades.", "Familiar"],
  ["A experiência foi muito positiva. Profissional atenciosa, clara e humana.", "Paciente"],
  ["Finalmente encontramos um espaço onde nossa família se sentiu realmente compreendida.", "Familiar"],
  ["Um atendimento delicado, profissional e acolhedor. Fez diferença para nossa família.", "Familiar"],
];
const faqs = [
  ["O atendimento pode ser presencial e online?", "Sim. O Espaço Mente Brilhante oferece atendimento presencial e online, de acordo com a modalidade disponível e adequada ao acompanhamento."],
  ["Como saber qual atendimento é indicado?", "O primeiro contato é uma oportunidade para compreender a necessidade e orientar sobre o caminho de cuidado mais adequado."],
  ["A avaliação neuropsicológica é para qualquer idade?", "A indicação depende da demanda, do objetivo da avaliação e das características da pessoa. A orientação é feita de forma individualizada."],
  ["Como faço para agendar?", "Clique em qualquer botão de WhatsApp da página e envie uma mensagem. A equipe poderá orientar os próximos passos."],
];

const btn = "inline-flex items-center justify-center gap-2 rounded-full bg-[#c99b4d] px-7 py-4 font-semibold text-[#17110a] shadow-[0_12px_35px_rgba(201,155,77,.22)] transition hover:-translate-y-0.5 hover:shadow-[0_18px_45px_rgba(201,155,77,.3)]";
const outline = "inline-flex items-center justify-center gap-2 rounded-full border border-[#c99b4d]/45 px-7 py-4 font-semibold text-[#dcb66d] transition hover:bg-[#c99b4d]/10";

function Index() {
  const [mobile, setMobile] = useState(false);
  const [faq, setFaq] = useState<number | null>(null);
  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobile(false); };
  return <div className="min-h-screen overflow-x-hidden bg-[#080706] text-[#f8f3e9]">
    <style>{`@keyframes belt{from{transform:translateX(0)}to{transform:translateX(-50%)}}.belt{animation:belt 38s linear infinite;width:max-content}.belt:hover{animation-play-state:paused}.gold-line{background:linear-gradient(90deg,transparent,#d6aa5c,transparent)}@media(max-width:640px){.belt{animation-duration:30s}}`}</style>

    <header className="fixed inset-x-0 top-0 z-50 border-b border-[#d0a45a]/15 bg-[#080706]/82 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
        <button onClick={() => go("inicio")} className="flex items-center gap-3 text-left"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-[#d0a45a]/45 bg-[#d0a45a]/10 text-[#e0b96d]"><Brain /></span><span><b className="block font-serif text-lg tracking-wide text-[#e0b96d]">ESPAÇO MENTE</b><small className="text-[10px] uppercase tracking-[.3em] text-white/55">Brilhante</small></span></button>
        <nav className="hidden items-center gap-6 text-sm lg:flex"><button onClick={() => go("dor")}>Sua jornada</button><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button><a href={wa} target="_blank" rel="noreferrer" className={btn + " px-5 py-2.5"}>Agendar</a></nav>
        <button className="lg:hidden" onClick={() => setMobile(!mobile)} aria-label="Abrir menu">{mobile ? <X /> : <Menu />}</button>
      </div>
      <AnimatePresence>{mobile && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden border-t border-[#d0a45a]/15 bg-[#100d0a] px-5 pb-5 lg:hidden"><div className="flex flex-col gap-4 pt-5 text-center"><button onClick={() => go("dor")}>Sua jornada</button><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button><a href={wa} target="_blank" rel="noreferrer" className={btn}>Agendar pelo WhatsApp</a></div></motion.div>}</AnimatePresence>
    </header>

    <main id="inicio">
      <section className="relative overflow-hidden px-5 pb-24 pt-36 lg:min-h-[760px] lg:px-8 lg:pt-44"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_28%,rgba(207,164,83,.18),transparent_30%),radial-gradient(circle_at_15%_75%,rgba(222,198,155,.06),transparent_28%)]"/><div className="absolute right-[-10%] top-24 h-80 w-80 rounded-full border border-[#d0a45a]/10 blur-2xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.08fr_.92fr]">
        <motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><span className="inline-flex items-center gap-2 rounded-full border border-[#d0a45a]/30 bg-[#d0a45a]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.22em] text-[#e0b96d]"><Sparkles className="h-4 w-4"/> Presencial e online</span><h1 className="mt-7 max-w-4xl font-serif text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">Cuidar da mente é <span className="text-[#dcb66d]">transformar vidas.</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/68 sm:text-xl">Um espaço de acolhimento, compreensão e cuidado para você, sua família e suas necessidades.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Quero cuidar de mim <ArrowRight className="h-5 w-5"/></a><button onClick={() => go("servicos")} className={outline}>Conhecer os serviços</button></div><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm text-white/55"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#dcb66d]"/> Atendimento humanizado</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#dcb66d]"/> Olhar individualizado</span></div></motion.div>
        <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8 }} className="relative mx-auto w-full max-w-[500px]"><div className="rounded-[2.2rem] border border-[#d0a45a]/35 bg-gradient-to-br from-[#292117] via-[#12100d] to-[#090807] p-3 shadow-[0_35px_100px_rgba(0,0,0,.6)]"><div className="relative flex aspect-[4/4.7] items-center justify-center overflow-hidden rounded-[1.8rem] bg-[#17130e]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_25%,rgba(215,171,91,.18),transparent_32%)]"/><div className="relative text-center px-8"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border border-[#d0a45a]/45 bg-[#d0a45a]/10 text-[#e0b96d]"><Brain className="h-12 w-12"/></div><p className="mt-7 text-xs font-bold uppercase tracking-[.3em] text-[#dcb66d]">Espaço Mente Brilhante</p><h2 className="mt-4 font-serif text-3xl leading-tight sm:text-4xl">Compreender. Acolher. Desenvolver.</h2><p className="mx-auto mt-4 max-w-sm text-sm leading-relaxed text-white/50">Cada pessoa é única. O cuidado também deve ser.</p></div></div></div><div className="absolute -bottom-5 -left-3 rounded-2xl border border-[#d0a45a]/30 bg-[#17130f]/95 px-5 py-4 shadow-xl backdrop-blur"><p className="text-[10px] uppercase tracking-wider text-white/40">Responsável técnica</p><p className="font-semibold text-[#e0b96d]">Francineia Magalhães</p><p className="text-xs text-white/55">Neuropsicóloga Clínica · CRP 10/06883</p></div></motion.div>
      </div></section>

      <section id="dor" className="bg-[#f0e9dd] px-5 py-24 text-[#19140e] lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#936c32]">Talvez você esteja vivendo isso</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Quando a mente pede atenção, continuar sozinho pode ser ainda mais difícil.</h2><p className="mt-6 text-lg leading-relaxed text-[#19140e]/65">Ansiedade, dificuldades de aprendizagem, desafios comportamentais, dúvidas sobre desenvolvimento ou simplesmente a sensação de que algo não está bem podem trazer insegurança para a rotina.</p><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-8"}>Conversar sobre o que estou vivendo <ArrowRight className="h-5 w-5"/></a></div><div className="grid gap-4 sm:grid-cols-2">{["Você sente que não consegue organizar o que está acontecendo?","Seu filho apresenta dificuldades que precisam ser melhor compreendidas?","Há comportamentos, emoções ou aprendizagem gerando preocupação?","Você gostaria de ter orientação profissional para dar o próximo passo?"].map((t,i)=><div key={i} className="rounded-3xl border border-[#8d672f]/15 bg-white/65 p-6 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#c99b4d]/12 font-serif text-lg text-[#936c32]">0{i+1}</span><p className="mt-5 font-medium leading-relaxed">{t}</p></div>)}</div></div></div></section>

      <section className="bg-[#11100d] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dcb66d]">A solução começa com um primeiro passo</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-4xl sm:text-5xl">Você não precisa ter todas as respostas para começar a buscar compreensão.</h2><p className="mx-auto mt-5 max-w-2xl text-white/55">O cuidado é construído com escuta, avaliação quando indicada, orientação e estratégias que respeitam a realidade de cada pessoa.</p><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-8"}>Falar pelo WhatsApp <MessageCircle className="h-5 w-5"/></a></div></section>

      <section id="sobre" className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div className="relative"><div className="aspect-[4/5] rounded-[2.2rem] border border-[#d0a45a]/35 bg-gradient-to-br from-[#252016] via-[#12100d] to-[#090807] p-3 shadow-2xl"><div className="flex h-full flex-col items-center justify-center rounded-[1.8rem] border border-white/5 bg-[#17130e] px-8 text-center"><div className="flex h-24 w-24 items-center justify-center rounded-full border border-dashed border-[#d0a45a]/45 bg-[#d0a45a]/8 text-[#dcb66d]"><span className="text-3xl">✦</span></div><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-[#dcb66d]">Espaço para sua foto</p><p className="mt-2 max-w-xs text-sm leading-relaxed text-white/42">Área reservada para adicionar a foto profissional da Francineia.</p></div></div><div className="absolute -bottom-4 right-0 rounded-2xl border border-[#d0a45a]/25 bg-[#18140f] px-5 py-4"><p className="font-serif text-xl text-[#e0b96d]">Francineia</p><p className="text-xs text-white/50">CRP 10/06883</p></div></div><div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dcb66d]">Quem sou eu</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Francineia Magalhães</h2><p className="mt-3 text-[#dcb66d]">Neuropsicóloga Clínica · CRP 10/06883</p><div className="mt-7 space-y-5 text-white/64 leading-relaxed"><p>Meu propósito é oferecer um espaço de acolhimento, compreensão e cuidado, unindo conhecimento científico a uma escuta verdadeiramente humanizada.</p><p>Cada pessoa chega com uma história, desafios e potencialidades diferentes. Por isso, o acompanhamento é pensado de forma individualizada, respeitando o momento e as necessidades de cada paciente.</p><p>O objetivo é caminhar junto, compreender o que está acontecendo e construir estratégias que façam sentido para a vida real.</p></div><a href={wa} target="_blank" rel="noreferrer" className={outline + " mt-8"}>Falar com Francineia <ArrowRight className="h-5 w-5"/></a></div></div></section>

      <section id="servicos" className="overflow-hidden bg-[#f4eee5] py-24 text-[#17130e]"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#936c32]">Nossos serviços</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Um cuidado pensado para diferentes necessidades</h2><p className="mx-auto mt-4 max-w-2xl text-[#17130e]/60">Os cards passam continuamente como uma esteira. Passe o mouse para pausar e escolha qualquer atendimento pelo botão.</p></div><div className="mt-12 overflow-hidden"><div className="belt flex gap-5">{[...services,...services].map(([icon,title,text],i)=><a href={wa} target="_blank" rel="noreferrer" key={`${title}-${i}`} className="w-[290px] shrink-0 rounded-[1.6rem] border border-[#241d13]/10 bg-white p-7 text-left shadow-[0_12px_35px_rgba(44,31,16,.08)] transition hover:-translate-y-2 hover:border-[#bd8d3d]/45 hover:shadow-[0_20px_45px_rgba(44,31,16,.14)]"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#c99b4d]/12 text-3xl">{icon}</span><h3 className="mt-5 min-h-[54px] font-serif text-xl font-bold">{title}</h3><p className="mt-2 min-h-[62px] text-sm leading-relaxed text-[#17130e]/58">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#936c32]">Agendar atendimento <ArrowRight className="h-4 w-4"/></span></a>)}</div></div><div className="mx-auto mt-12 max-w-3xl px-5 text-center"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Quero encontrar o atendimento ideal para mim <ArrowRight className="h-5 w-5"/></a></div></section>

      <section id="como" className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dcb66d]">Como funciona</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Um caminho simples para começar</h2><div className="mt-14 grid gap-5 md:grid-cols-4">{[["01","Converse conosco","Clique no WhatsApp e conte brevemente o que você procura."],["02","Entenda a necessidade","O primeiro contato ajuda a orientar o próximo passo."],["03","Construa seu cuidado","O acompanhamento considera sua realidade e suas necessidades."],["04","Avance com segurança","Você segue com orientação e acompanhamento profissional."]].map(([n,t,d])=><div key={n} className="rounded-3xl border border-white/10 bg-[#11100d] p-7 text-left"><span className="font-serif text-4xl text-[#dcb66d]">{n}</span><h3 className="mt-5 font-serif text-2xl">{t}</h3><p className="mt-3 text-sm leading-relaxed text-white/50">{d}</p><a href={wa} target="_blank" rel="noreferrer" className="mt-5 inline-flex text-sm font-semibold text-[#dcb66d]">Falar pelo WhatsApp →</a></div>)}</div></div></section>

      <section id="depoimentos" className="overflow-hidden bg-[#0d0b09] py-24"><div className="px-5 text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dcb66d]">Depoimentos</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Experiências de quem encontrou acolhimento</h2><p className="mx-auto mt-4 max-w-2xl text-white/50">Relatos ilustrativos de experiência de atendimento.</p></div><div className="mt-12 overflow-hidden"><div className="belt flex gap-5" style={{ animationDuration: "32s" }}>{[...testimonials,...testimonials].map(([text,name],i)=><div key={`${name}-${i}`} className="w-[340px] shrink-0 rounded-[1.7rem] border border-[#d0a45a]/18 bg-[#17130e] p-7 shadow-xl"><div className="flex gap-1 text-[#e0b96d]">{[1,2,3,4,5].map(n=><span key={n}>★</span>)}</div><p className="mt-6 min-h-[100px] text-[15px] leading-relaxed text-white/70">“{text}”</p><div className="mt-6 border-t border-white/8 pt-5"><p className="font-semibold text-white">{name}</p><p className="mt-1 text-xs text-[#dcb66d]">Avaliação ★★★★★</p></div></div>)}</div></div><div className="mt-12 text-center"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Quero viver essa experiência <ArrowRight className="h-5 w-5"/></a></div></section>

      <section id="faq" className="bg-[#f0e9dd] px-5 py-24 text-[#19140e] lg:px-8"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#936c32]">Dúvidas</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Antes de dar o primeiro passo</h2></div><div className="mt-12 space-y-3">{faqs.map(([q,a],i)=><div key={q} className="overflow-hidden rounded-2xl border border-[#19140e]/10 bg-white/65"><button onClick={() => setFaq(faq === i ? null : i)} className="flex w-full items-center justify-between gap-5 px-6 py-5 text-left font-semibold"><span>{q}</span><ChevronDown className={`h-5 w-5 shrink-0 text-[#936c32] transition ${faq===i?"rotate-180":""}`}/></button><AnimatePresence>{faq===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p className="px-6 pb-6 text-sm leading-relaxed text-[#19140e]/60">{a}</p></motion.div>}</AnimatePresence></div>)}</div><div className="mt-10 text-center"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Tirar minha dúvida pelo WhatsApp <MessageCircle className="h-5 w-5"/></a></div></div></section>

      <section className="relative overflow-hidden px-5 py-24 lg:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(207,164,83,.16),transparent_40%)]"/><div className="relative mx-auto max-w-4xl rounded-[2.4rem] border border-[#d0a45a]/30 bg-gradient-to-br from-[#211b13] to-[#0f0d0a] px-7 py-14 text-center shadow-[0_30px_100px_rgba(0,0,0,.45)] sm:px-12"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dcb66d]">Seu próximo passo</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Cuidar da mente também é uma forma de cuidar da vida.</h2><p className="mx-auto mt-5 max-w-2xl text-white/55">Se você sente que chegou a hora de buscar orientação, fale conosco e saiba como começar.</p><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-8"}>Agendar atendimento pelo WhatsApp <ArrowRight className="h-5 w-5"/></a></div></section>
    </main>

    <a href={wa} target="_blank" rel="noreferrer" aria-label="Falar no WhatsApp" className="fixed bottom-5 right-5 z-50 flex h-16 w-16 items-center justify-center rounded-full bg-[#25D366] text-white shadow-[0_12px_35px_rgba(0,0,0,.35)] transition hover:scale-110"><MessageCircle className="h-7 w-7"/></a>
  </div>;
}
