import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Brain, Check, ChevronDown, HeartHandshake, Instagram, MessageCircle, Menu, Sparkles, Stethoscope, X } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Espaço Mente Brilhante | Neuropsicologia e Saúde Mental" },
    { name: "description", content: "Ciência, acolhimento e estratégias para promover desenvolvimento integral e qualidade de vida." },
  ] }), component: Index,
});

const wa = "https://wa.me/5592991819513";
const services = [
  ["🧩", "Atendimento para TEA", "Acolhimento e estratégias individualizadas."],
  ["🧠", "Atendimento para TDAH", "Compreensão e estratégias para diferentes necessidades."],
  ["📚", "Dificuldades de aprendizagem", "Investigação e intervenção individualizada."],
  ["💙", "Saúde Mental", "Escuta e cuidado para promover qualidade de vida."],
  ["✨", "TOD", "Atendimento com olhar individualizado."],
  ["🌿", "Ansiedade", "Acolhimento e desenvolvimento de recursos."],
  ["🌼", "Depressão", "Cuidado humanizado durante o acompanhamento."],
  ["📋", "Avaliação Neuropsicológica", "Compreensão de aspectos cognitivos, emocionais e funcionais."],
  ["💬", "Atendimento Psicológico", "Escuta profissional em ambiente seguro."],
  ["🧩", "Intervenção ABA", "Estratégias baseadas em princípios da Análise do Comportamento Aplicada."],
];
const testimonials = [
  ["Fui recebida com muito acolhimento e atenção. Me senti segura desde o primeiro atendimento.", "Paciente"],
  ["O atendimento foi muito cuidadoso e individualizado. Conseguimos entender melhor nossas necessidades.", "Familiar"],
  ["A experiência foi muito positiva. Profissional atenciosa, clara e humana.", "Paciente"],
  ["Finalmente encontramos um espaço onde nossa família se sentiu realmente compreendida.", "Familiar"],
  ["Um atendimento delicado, profissional e acolhedor. Fez diferença para nossa família.", "Familiar"],
];
const faqs = [
  ["O atendimento pode ser presencial e online?", "Sim. O Espaço Mente Brilhante oferece atendimento presencial e online, de acordo com a modalidade disponível e adequada ao acompanhamento."],
  ["Como saber qual atendimento é indicado?", "O primeiro contato é uma oportunidade para compreender a necessidade e orientar sobre o caminho de cuidado mais adequado."],
  ["A avaliação neuropsicológica é para qualquer idade?", "A indicação depende da demanda, do objetivo da avaliação e das características da pessoa. A orientação é feita de forma individualizada."],
  ["Como faço para agendar?", "Clique em qualquer botão de WhatsApp da página e envie uma mensagem. A equipe poderá orientar os próximos passos."],
];

const btn = "inline-flex items-center justify-center gap-2 rounded-full bg-[#d4aa5d] px-7 py-4 font-semibold text-[#17110a] shadow-[0_14px_38px_rgba(212,170,93,.2)] transition hover:-translate-y-0.5 hover:bg-[#e0bb72]";
const outline = "inline-flex items-center justify-center gap-2 rounded-full border border-[#d4aa5d]/45 px-7 py-4 font-semibold text-[#e2bf79] transition hover:bg-[#d4aa5d]/10";

function Index() {
  const [mobile, setMobile] = useState(false);
  const [faq, setFaq] = useState<number | null>(null);
  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobile(false); };
  return <div className="min-h-screen overflow-x-hidden bg-[#070605] text-[#f8f2e7]">
    <style>{`@keyframes belt{from{transform:translateX(0)}to{transform:translateX(-50%)}}.belt{animation:belt 38s linear infinite;width:max-content}.belt:hover{animation-play-state:paused}.gold-line{background:linear-gradient(90deg,transparent,#d4aa5d,transparent)}@media(max-width:640px){.belt{animation-duration:30s}}`}</style>

    {/* Cabeçalho compacto, sem ocupar a tela */}
    <header className="relative z-40 border-b border-[#d4aa5d]/15 bg-[#090806]">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
        <button onClick={() => go("inicio")} className="flex items-center gap-3 text-left"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-[#d4aa5d]/45 bg-[#d4aa5d]/10 text-[#e3bd75]"><Brain /></span><span><b className="block font-serif text-lg tracking-wide text-[#e3bd75]">ESPAÇO MENTE</b><small className="text-[10px] uppercase tracking-[.3em] text-white/50">Brilhante</small></span></button>
        <nav className="hidden items-center gap-7 text-sm lg:flex"><button onClick={() => go("dor")}>Sua jornada</button><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button><a href={wa} target="_blank" rel="noreferrer" className={btn + " px-5 py-2.5"}>Agendar</a></nav>
        <button className="lg:hidden" onClick={() => setMobile(!mobile)} aria-label="Abrir menu">{mobile ? <X /> : <Menu />}</button>
      </div>
      <AnimatePresence>{mobile && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden border-t border-[#d4aa5d]/15 bg-[#100d0a] px-5 pb-5 lg:hidden"><div className="flex flex-col gap-4 pt-5 text-center"><button onClick={() => go("dor")}>Sua jornada</button><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button><a href={wa} target="_blank" rel="noreferrer" className={btn}>Agendar pelo WhatsApp</a></div></motion.div>}</AnimatePresence>
    </header>

    <main id="inicio">
      {/* 1 — HERO */}
      <section className="relative overflow-hidden px-5 pb-24 pt-24 lg:min-h-[720px] lg:px-8 lg:pt-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_76%_28%,rgba(212,170,93,.17),transparent_30%),radial-gradient(circle_at_15%_75%,rgba(222,198,155,.05),transparent_28%)]"/><div className="absolute right-[-12%] top-20 h-96 w-96 rounded-full border border-[#d4aa5d]/10 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 text-center lg:grid-cols-[1.08fr_.92fr] lg:text-left">
        <motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="mx-auto max-w-3xl lg:mx-0"><span className="inline-flex items-center gap-2 rounded-full border border-[#d4aa5d]/30 bg-[#d4aa5d]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.22em] text-[#e2bf79]"><Sparkles className="h-4 w-4"/> Presencial e online</span><h1 className="mt-7 font-serif text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">Cuidar da mente é <span className="text-[#dfba70]">transformar vidas.</span></h1><p className="mt-7 text-lg leading-relaxed text-white/65 sm:text-xl">Um espaço de acolhimento, compreensão e cuidado para você, sua família e suas necessidades.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row lg:justify-start"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Quero cuidar de mim <ArrowRight className="h-5 w-5"/></a><button onClick={() => go("servicos")} className={outline}>Conhecer os serviços</button></div><div className="mt-8 flex flex-wrap justify-center gap-x-7 gap-y-3 text-sm text-white/50 lg:justify-start"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#dfba70]"/> Atendimento humanizado</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#dfba70]"/> Olhar individualizado</span></div></motion.div>
        <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8 }} className="mx-auto w-full max-w-[480px]"><div className="rounded-[2.4rem] border border-[#d4aa5d]/35 bg-gradient-to-br from-[#2a2115] via-[#12100c] to-[#090807] p-3 shadow-[0_35px_100px_rgba(0,0,0,.65)]"><div className="relative flex aspect-[4/4.5] items-center justify-center overflow-hidden rounded-[2rem] bg-[#14110d]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_42%,rgba(218,176,94,.2),transparent_30%)]"/><div className="relative flex flex-col items-center justify-center px-8 text-center"><div className="flex h-28 w-28 items-center justify-center rounded-full border border-[#d4aa5d]/50 bg-[#d4aa5d]/10 text-[#e3bd75] shadow-[0_0_70px_rgba(212,170,93,.12)]"><Brain className="h-14 w-14"/></div><div className="gold-line mt-8 h-px w-28"/><p className="mt-6 max-w-xs font-serif text-2xl leading-snug text-white/90">Um espaço para cuidar do que realmente importa.</p></div></div></div></motion.div>
      </div></section>

      {/* 2 — DOR */}
      <section id="dor" className="relative overflow-hidden bg-[#eee5d7] px-5 py-24 text-[#19140e] lg:px-8"><div className="absolute left-0 top-0 h-40 w-full bg-[radial-gradient(circle_at_50%_0%,rgba(190,145,70,.12),transparent_60%)]"/><div className="relative mx-auto max-w-7xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#946b2d]">Sua jornada merece atenção</p><h2 className="mx-auto mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-5xl">Quando algo não vai bem, buscar compreensão pode mudar a forma de viver essa fase.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-[#19140e]/65">Ansiedade, dificuldades de aprendizagem, desafios comportamentais, dúvidas sobre desenvolvimento ou aquela sensação de que algo precisa ser melhor compreendido podem trazer insegurança para a rotina.</p><div className="mx-auto mt-12 grid max-w-5xl gap-5 sm:grid-cols-2">{["Você sente que não consegue organizar o que está acontecendo?","Seu filho apresenta dificuldades que precisam ser melhor compreendidas?","Há comportamentos, emoções ou aprendizagem gerando preocupação?","Você gostaria de ter orientação profissional para dar o próximo passo?"].map((t,i)=><div key={i} className="rounded-[1.7rem] border border-[#8d672f]/15 bg-white/70 p-7 text-center shadow-[0_12px_35px_rgba(50,35,15,.06)]"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-[#c99b4d]/15 font-serif text-lg text-[#946b2d]">0{i+1}</span><p className="mt-5 font-medium leading-relaxed">{t}</p></div>)}</div><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-10"}>Quero conversar sobre isso <ArrowRight className="h-5 w-5"/></a></div></section>

      {/* 3 — SERVIÇOS */}
      <section id="servicos" className="overflow-hidden bg-[#0b0907] py-24 text-white"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dfba70]">Nossos serviços</p><h2 className="mx-auto mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-5xl">Cuidado pensado para diferentes necessidades</h2><p className="mx-auto mt-5 max-w-2xl text-white/50">Conheça algumas possibilidades de atendimento. Os cards passam continuamente como uma esteira.</p></div><div className="mt-12 overflow-hidden"><div className="belt flex gap-5">{[...services,...services].map(([icon,title,text],i)=><a href={wa} target="_blank" rel="noreferrer" key={`${title}-${i}`} className="w-[290px] shrink-0 rounded-[1.8rem] border border-[#d4aa5d]/16 bg-gradient-to-b from-[#18130d] to-[#100d0a] p-7 text-center shadow-[0_18px_50px_rgba(0,0,0,.28)] transition hover:-translate-y-2 hover:border-[#d4aa5d]/45"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl border border-[#d4aa5d]/18 bg-[#d4aa5d]/10 text-3xl">{icon}</span><h3 className="mt-5 min-h-[54px] font-serif text-xl font-bold text-[#f8f0e2]">{title}</h3><p className="mt-2 min-h-[62px] text-sm leading-relaxed text-white/50">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#dfba70]">Agendar atendimento <ArrowRight className="h-4 w-4"/></span></a>)}</div></div><div className="mt-12 text-center"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Quero encontrar o atendimento ideal <ArrowRight className="h-5 w-5"/></a></div></section>

      {/* SOLUÇÃO */}
      <section className="bg-[#17120d] px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dfba70]">Um novo caminho pode começar aqui</p><h2 className="mx-auto mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-5xl">Você não precisa ter todas as respostas para dar o primeiro passo.</h2><div className="mx-auto mt-12 grid gap-5 md:grid-cols-3">{[["Escuta", "Um espaço seguro para falar, ser compreendido e olhar para suas necessidades."],["Compreensão", "Quando necessário, a avaliação ajuda a organizar informações e ampliar a compreensão."],["Estratégias", "O cuidado busca caminhos individualizados que façam sentido para a vida real."]].map(([t,d],i)=><div key={t} className="rounded-[1.8rem] border border-[#d4aa5d]/18 bg-[#0f0c09] p-8 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-[#d4aa5d]/30 bg-[#d4aa5d]/10 font-serif text-lg text-[#dfba70]">0{i+1}</span><h3 className="mt-5 font-serif text-2xl">{t}</h3><p className="mt-3 leading-relaxed text-white/50">{d}</p></div>)}</div><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-10"}>Falar pelo WhatsApp <MessageCircle className="h-5 w-5"/></a></div></section>

      {/* QUEM SOU */}
      <section id="sobre" className="bg-[#f4ede2] px-5 py-24 text-[#19140e] lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div className="relative mx-auto w-full max-w-[430px]"><div className="aspect-[4/5] rounded-[2.4rem] border border-[#aa7a32]/30 bg-gradient-to-br from-[#d8c09a] via-[#b99358] to-[#765321] p-3 shadow-[0_25px_70px_rgba(71,48,19,.2)]"><div className="flex h-full flex-col items-center justify-center rounded-[2rem] border border-white/35 bg-[#efe5d4] px-8 text-center"><div className="flex h-24 w-24 items-center justify-center rounded-full border border-[#b8893e]/35 bg-[#b8893e]/10 text-[#9b6e2e]"><span className="font-serif text-4xl">F</span></div><p className="mt-6 text-xs font-bold uppercase tracking-[.25em] text-[#946b2d]">Foto profissional</p><p className="mt-2 max-w-xs text-sm leading-relaxed text-[#19140e]/45">Área reservada para adicionar a foto da Francineia.</p></div></div></div><div className="text-center lg:text-left"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#946b2d]">Quem sou eu</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Francineia Magalhães</h2><p className="mt-3 font-medium text-[#a27635]">Neuropsicóloga Clínica · CRP 10/06883</p><div className="mx-auto mt-7 max-w-2xl space-y-5 leading-relaxed text-[#19140e]/65 lg:mx-0"><p>Meu propósito é oferecer um espaço de acolhimento, compreensão e cuidado, unindo conhecimento científico a uma escuta verdadeiramente humanizada.</p><p>Cada pessoa chega com uma história, desafios e potencialidades diferentes. Por isso, o acompanhamento é pensado de forma individualizada, respeitando o momento e as necessidades de cada paciente.</p><p>O objetivo é caminhar junto, compreender o que está acontecendo e construir estratégias que façam sentido para a vida real.</p></div><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-8"}>Falar com Francineia <ArrowRight className="h-5 w-5"/></a></div></div></section>

      {/* COMO FUNCIONA */}
      <section id="como" className="bg-[#090806] px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dfba70]">Como funciona</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Um caminho simples para começar</h2><div className="mt-14 grid gap-5 md:grid-cols-4">{[["01","Converse conosco","Clique no WhatsApp e conte brevemente o que você procura."],["02","Entenda a necessidade","O primeiro contato ajuda a orientar o próximo passo."],["03","Construa seu cuidado","O acompanhamento considera sua realidade e suas necessidades."],["04","Avance com segurança","Você segue com orientação e acompanhamento profissional."]].map(([n,t,d])=><div key={n} className="rounded-[1.8rem] border border-[#d4aa5d]/15 bg-[#12100c] p-7 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-[#d4aa5d]/25 bg-[#d4aa5d]/10 font-serif text-lg text-[#dfba70]">{n}</span><h3 className="mt-5 font-serif text-2xl">{t}</h3><p className="mt-3 text-sm leading-relaxed text-white/50">{d}</p><a href={wa} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-[#dfba70]">Falar pelo WhatsApp <ArrowRight className="h-4 w-4"/></a></div>)}</div></div></section>

      {/* DEPOIMENTOS */}
      <section id="depoimentos" className="overflow-hidden bg-[#eee5d7] py-24 text-[#19140e]"><div className="px-5 text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#946b2d]">Depoimentos</p><h2 className="mx-auto mt-4 max-w-4xl font-serif text-4xl sm:text-5xl">Experiências de quem encontrou acolhimento</h2><p className="mx-auto mt-4 max-w-2xl text-[#19140e]/50">Relatos ilustrativos de experiência de atendimento.</p></div><div className="mt-12 overflow-hidden"><div className="belt flex gap-5" style={{ animationDuration: "32s" }}>{[...testimonials,...testimonials].map(([text,name],i)=><div key={`${name}-${i}`} className="w-[340px] shrink-0 rounded-[1.8rem] border border-[#9c7130]/15 bg-white p-7 text-center shadow-[0_15px_40px_rgba(58,40,17,.08)]"><div className="flex justify-center gap-1 text-[#c3923e]">{[1,2,3,4,5].map(n=><span key={n}>★</span>)}</div><p className="mt-6 min-h-[100px] text-[15px] leading-relaxed text-[#19140e]/68">“{text}”</p><div className="mt-6 border-t border-[#19140e]/10 pt-5"><p className="font-semibold">{name}</p><p className="mt-1 text-xs font-bold tracking-wider text-[#946b2d]">★★★★★</p></div></div>)}</div></div><div className="mt-12 text-center"><a href={wa} target="_blank" rel="noreferrer" className={btn}>Quero conversar pelo WhatsApp <MessageCircle className="h-5 w-5"/></a></div></section>

      {/* FAQ */}
      <section id="faq" className="bg-[#f4ede2] px-5 py-24 text-[#19140e] lg:px-8"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#946b2d]">Dúvidas</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Antes de dar o primeiro passo</h2><div className="mt-12 space-y-3 text-left">{faqs.map(([q,a],i)=><div key={q} className="overflow-hidden rounded-2xl border border-[#19140e]/10 bg-white/70"><button onClick={() => setFaq(faq === i ? null : i)} className="flex w-full items-center justify-between gap-5 px-6 py-5 text-left font-semibold"><span>{q}</span><ChevronDown className={`h-5 w-5 shrink-0 text-[#946b2d] transition ${faq===i?"rotate-180":""}`}/></button><AnimatePresence>{faq===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p className="px-6 pb-6 text-sm leading-relaxed text-[#19140e]/60">{a}</p></motion.div>}</AnimatePresence></div>)}</div><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-10"}>Tirar minha dúvida pelo WhatsApp <MessageCircle className="h-5 w-5"/></a></div></section>

      {/* CTA FINAL */}
      <section className="relative overflow-hidden bg-[#080706] px-5 py-24 lg:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(212,170,93,.15),transparent_42%)]"/><div className="relative mx-auto max-w-4xl rounded-[2.5rem] border border-[#d4aa5d]/30 bg-gradient-to-br from-[#211a11] to-[#0e0c09] px-7 py-14 text-center shadow-[0_30px_100px_rgba(0,0,0,.5)] sm:px-12"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#dfba70]">Seu próximo passo</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Cuidar da mente também é uma forma de cuidar da vida.</h2><p className="mx-auto mt-5 max-w-2xl text-white/52">Se você sente que chegou a hora de buscar orientação, fale conosco e saiba como começar.</p><a href={wa} target="_blank" rel="noreferrer" className={btn + " mt-8"}>Agendar atendimento pelo WhatsApp <ArrowRight className="h-5 w-5"/></a></div></section>
    </main>

    {/* RODAPÉ */}
    <footer className="border-t border-[#d4aa5d]/15 bg-[#0d0b08] px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 text-center md:grid-cols-[1.2fr_.8fr_.8fr] md:text-left"><div><div className="flex items-center justify-center gap-3 md:justify-start"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-[#d4aa5d]/40 bg-[#d4aa5d]/10 text-[#dfba70]"><Brain/></span><div><p className="font-serif text-lg tracking-wide text-[#dfba70]">ESPAÇO MENTE</p><p className="text-[10px] uppercase tracking-[.3em] text-white/40">Brilhante</p></div></div><p className="mx-auto mt-5 max-w-md text-sm leading-relaxed text-white/45 md:mx-0">Ciência, acolhimento e cuidado para promover compreensão, desenvolvimento e qualidade de vida.</p></div><div><p className="font-semibold text-white">Navegação</p><div className="mt-4 flex flex-col gap-3 text-sm text-white/50"><button onClick={() => go("sobre")}>Quem sou</button><button onClick={() => go("servicos")}>Serviços</button><button onClick={() => go("como")}>Como funciona</button><button onClick={() => go("depoimentos")}>Depoimentos</button></div></div><div><p className="font-semibold text-white">Fale conosco</p><a href={wa} target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-center gap-2 text-sm text-[#dfba70] md:justify-start"><MessageCircle className="h-4 w-4"/> WhatsApp</a><a href="https://instagram.com" target="_blank" rel="noreferrer" className="mt-3 flex items-center justify-center gap-2 text-sm text-white/50 md:justify-start"><Instagram className="h-4 w-4"/> Instagram</a></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/8 pt-7 text-center text-xs text-white/30">© {new Date().getFullYear()} Espaço Mente Brilhante. Todos os direitos reservados.</div></footer>

    <a href={wa} target="_blank" rel="noreferrer" aria-label="Falar no WhatsApp" className="fixed bottom-5 right-5 z-50 flex h-16 w-16 items-center justify-center rounded-full bg-[#25D366] text-white shadow-[0_12px_35px_rgba(0,0,0,.35)] transition hover:scale-110"><MessageCircle className="h-7 w-7"/></a>
  </div>;
}
